server:
   port: 8012
   
datasources:
   local:
     # url: jdbc:h2:tcp://localhost/~/localdb
     jdbc-url: jdbc:h2:~/test
     username: sa
     driver-class-name: org.h2.Driver
     type: com.zaxxer.hikari.HikariDataSource
     min-idle: 1
     max-active: 2
   remote:
     jdbc-url: jdbc:h2:tcp://localhost/~/remote
     driver-class-name: org.h2.Driver
     type: com.zaxxer.hikari.HikariDataSource
     min-idle: 0
     max-active: 2

spring:
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true
      properties:
         hibernate.enable_lazy_load_no_trans: false
      hibernate:
         # To change the field naming converntion to handle the Camel style without adding underline 
         naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
         format_sql: true
logging:
   pattern:
      console: "%d %-5level %logger : %msg%n"
   level:
      root: ERROR
      org.hibernate.SQL: DEBUG
             